<a href="https://colab.research.google.com/github/tekebim/exo-algo/blob/master/exo_algo_12102020.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 2.1 La somme : Ecrire un algorithme calculant la somme des valeurs d’un tableau

from random import randint
# define the min / max for values + lenght of arrays
min, max = -10, 10
myArrayLenght = 10
myArray = [randint(min,max) for _ in range(myArrayLenght)]
sumValue = 0

# loop for each value in array
for eachVal in myArray:
  # test if value is an integer or float
  if(isinstance(eachVal, (int,float))):
    # sum the value to the global sum
    sumValue = sumValue + eachVal
  else:
    # display an error message for current value    
    print('La valeur :',eachVal, ' n\'étant pas un nombre, elle ne peut pas être additionnée aux autres éléments de la liste')
# display the result
print('Somme des valeurs des éléménts du tableau :', sumValue)
print(myArray)

Somme des valeurs des éléménts du tableau : 5
[0, 1, -2, -8, -8, 8, -8, 7, 6, 9]


In [ ]:
# 2.2 La somme - retour : Ecrire un algorithme constituant un tableau, a partir de deux tableaux de meme longueur prealablement saisis. Le nouveau tableau sera la somme des  elements des deux tableaux de depart.

from random import randint

# define the min / max for values + lenght of arrays
min, max = -100, 100
myArrayLenght = 10

# build arrays with random values
myFirstArray = [randint(min,max) for _ in range(myArrayLenght)]
mySecondArray = [randint(min,max) for _ in range(myArrayLenght)]

# create custom function to calculate the sum of each array's entries
def entriesSum(dataArray):
  sumValue = 0
  for element in dataArray:
    sumValue = sumValue + element
  return sumValue


# calculate the sum of first and second arrays, and place it on a third array 
myThirdArray = [entriesSum(myFirstArray) + entriesSum(mySecondArray)]
print('Tableau 1 :', myFirstArray)
print('Tableau 2 :', mySecondArray)
print('Tableau 3 :',myThirdArray, '(Somme tableaux 1 et 2)')


Tableau 1 : [-20, 76, -85, 43, -92, 93, 58, -34, 4, -72]
Tableau 2 : [14, -44, -96, -27, -98, 96, -57, -38, -69, -41]
Tableau 3 : [-389] (Somme tableaux 1 et 2)


In [ ]:
# 2.3 FacProduct : Toujours a partir de deux tableaux precedemment saisis, ecrire un algorithme qui calcule le ’FacProduct’ des deux tableaux. Pour calculer le ’FacProduct’, il faut multiplier chaque element du tableau1 par chaque element du tableau2, et additionner le tout.

from random import randint

min, max = -100, 100
myArrayLenght = 10

# build arrays with random values
myFirstArray = [randint(min,max) for _ in range(myArrayLenght)]
mySecondArray = [randint(min,max) for _ in range(myArrayLenght)]
# define start value
facProductValue = 0

# loop on primary array
for _, primaryElement in enumerate(myFirstArray):
  # loop on secondary array
  for _, secondaryElement in enumerate(mySecondArray):
    # sum the product of (primaryElement * secondaryElement)    
    facProductValue += primaryElement * secondaryElement

print('Résultat du FacProduct entre le tableau 1 et 2 :', facProductValue)

Résultat du FacProduct entre le tableau 1 et 2 : 6426


In [ ]:
# 2.4 Le plus grand : Ecrire un algorithme permettant a l’utilisateur de saisir un nombre determine de valeurs. Le programme, une fois la saisie terminee, renvoie la plus grande valeur en precisant quelle position elle occupe dans le tableau.

#from random import randint
#min, max = -10, 10
nbEntries = input('Saisissez le nombre d\'entrées constituant le tableau : ')
inputValues = []

# method to test if is a number like integer or float 
def isInteger(item):
  try:
    int(item)
    valid = True
  except ValueError:
    valid = False
  return valid

if(isInteger(nbEntries)):
  nbEntries = int(nbEntries)
  i = 1
  while(i <= nbEntries):    
    # randomly
    # inputValues = [randint(min,max) for _ in range(int(nbEntries))]
    labelInputTxt = ('Saisissez la valeur n°'+str(i)+': ')
    value = input(labelInputTxt)
    if(isInteger(value)):
      # or via user inputs
      inputValues.append(value)
    else:
      print('La valeur saisie n\'est pas un entier')
      break
    i += 1

  # create temporary variable
  tmpMax = inputValues[0]

  # loop on each index of array  
  for index, element in enumerate(inputValues):
    if element > tmpMax:
      tmpMax = element
      tmpIndex = index + 1
  print('La valeur maximale dans le tableau est :',tmpMax, 'et se situe à la position :', tmpIndex, 'dans le tableau')  
  print(inputValues)
else:
  print('Veuillez saisir un nombre entier pour constituer le tableau')

Saisissez le nombre d'entrées constituant le tableau : 4
Saisissez la valeur n°1: 1212
Saisissez la valeur n°2: -12
Saisissez la valeur n°3: 30
Saisissez la valeur n°4: 12121
La valeur maximale dans le tableau est : 30 et se situe à la position : 3 dans le tableau
['1212', '-12', '30', '12121']


In [ ]:
# correction 2.4 test

tailleListe = int(input('taille de la liste'))
liste = [0]*tailleListe
for i in range(tailleListe):
  liste[i] = int(input('valeur'))
print(liste)
max = liste[0]
for i in liste:
  if i > max :
    max = i
print(max)

# fonction max par defaut


In [ ]:
# 3 temps d'arret :
# definir une somme - tel que 


from fractions import Fraction

k = 1
n = 1

def Hn(n):
  Hn = (sum([k])*n) + Fraction(1,k)
  return Hn


#while Hn(n) > n:   
#  n += 1
#  alpha = Hn()

print(Hn(2))


# $Hn = \sum{k = 1}^n \frac{1}{k}$

3


In [ ]:

# Correction

n = 1
a = int(input('Reel a :'))
H = 0
while H < a :
  H = 0
  for k in range (1,n) :
    H += 1/k
  n +=1
print(n)

# other version
n = 1 
a = int(input('Reel a :'))
H = 0
while H < a :
  H += 1/n
  n += 1
print(n)

Reel a :11
33619
Reel a :11
33618


In [ ]:
# 3.2 equation de pell fermat

x = 0
y = 0
i = 1
j = 1
arrayValue = []

for i in range(101):
  for j in range(101):
    if((i*i)- (2*(j*j)) == 1):
      arrayValue.append([('x',i),('y',j)])

print(arrayValue)


[[('x', 1), ('y', 0)], [('x', 3), ('y', 2)], [('x', 17), ('y', 12)], [('x', 99), ('y', 70)]]


In [ ]:
# 3.2 equation de pell fermat

x = 0
y = 0
i = 1
j = 1
arrayValue = []

while i <= 100 :
  while j <= 100 :
    if((i*i)- (2*(j*j)) == 1):      
      arrayValue.append([('x',i),('y',j)])
    j += 1
  j = 0
  i += 1

print(arrayValue)


[[('x', 3), ('y', 2)], [('x', 17), ('y', 12)], [('x', 99), ('y', 70)]]


In [ ]:
x = 1
y = 1
s= 100
arrayValue = []

for x in range(1,s):
  for y in range(1,s):
    if((x*x)- (2*(y*y)) == 1):      
      arrayValue.append([('x',x),('y',y)])

print(arrayValue)

[[('x', 3), ('y', 2)], [('x', 17), ('y', 12)], [('x', 99), ('y', 70)]]


In [ ]:
# ax2 +bx+c=0

a = 1
b = 1
c = 1
x = 1

equation = (a*(x*x)) + (b*x) + c

discrimant = (b*b) - (4*a*c)

print(equation)
print(discrimant)

3
-3


variables a, b, c, x0, x1, x2, delta
saisir a, b, c
delta <- b2 - 4*a*c
si delta > 0 alors
  x1 <- (-b-racineCarre(delta))/2*a
  x2 <- (-b-racineCarre(delta))/2*a
  afficher "x1 = ".x1." et x2 = ".x2
sinon
  si delta = 0 alors
    x0 <- (-b)/2*a
    afficher "x0 = ".x0
  sinon
    afficher "pas de recherche"
  fin si
fin si

In [ ]:
from math import *
a = int(input('a ='))
b = int(input('b ='))
c = int(input('c ='))

delta = (b**2)-4*a*c

if delta > 0 :
  x1 = (-(b)-sqrt(delta))/2*a
  x2 = (-(b)-sqrt(delta))/2*a
  print('x1 - ',x1,' et x2 = ',x2)
else:
  if delta == 0 :
    x0 = (-(b))/(2*a)
    print('x0 =',x0 )
  else:
    print('pas de racine')

a =-3
b =-4
c =1
x1 -  1.9372539331937721  et x2 =  1.9372539331937721


In [ ]:
# 3.4 ( new version )

from math import *

a = int(input('a ='))
b = int(input('b ='))
c = int(input('c ='))

delta = (b*b)-4*a*c

def calculDelta(a,b,c):
  return (b*b)-4*a*c

if(calculDelta(a,b,c) > 0):
  x1 = (-(b)-sqrt(delta))/2*a
  x2 = (-(b)-sqrt(delta))/2*a
  print('x1 - ',x1,' et x2 = ',x2)
else :
  if(calculDelta(a,b,c) == 0):
    x0 = (-(b))/(2*a)
    print('x0 =',x0 )
  else:
    print('Pas de racine')
  

az²+ bz + c = 0 avec a≠0

In [ ]:
# 3.4

from math import *

a = int(input('a ='))
b = int(input('b ='))
c = int(input('c ='))

delta = (b*b)-4*a*c

def calculDelta(a,b,c):
  return (b*b)-4*a*c

if(calculDelta(a,b,c) > 0):
  x1 = (-b)-sqrt(delta)*i/2*a
  x2 = (-b)+sqrt(delta)*i/2*a
  print('x1 - ',x1,' et x2 = ',x2)
else :
  if(calculDelta(a,b,c) == 0):
    x0 = (-(b))/(2*a)
    print('x0 =',x0 )
  else:
    print('Pas de racine')
  

a =-3
b =-4
c =1
x1 -  797.7253933193772  et x2 =  -789.7253933193772


In [ ]:
# 3.4 correction
from math import *
import cmath

a = int(input('a ='))
b = int(input('b ='))
c = int(input('c ='))

delta = (b*b)-4*a*c
racineDelta = cmath.sqrt(delta)
# print('delta =',delta )

if delta > 0:
  x1 = ((-b)-sqrt(delta))/2*a
  x2 = ((-b)+sqrt(delta))/2*a
  print('x1 - ',x1,' et x2 = ',x2)
else :
  if(delta == 0):
    x0 = (-(b))/(2*a)
    print('x0 =',x0 )
  else:
    x1 = (-(b)-racineDelta)/2*a
    x2 = (-(b)+racineDelta)/2*a
    print('x1 - ',x1,'i et x2 = ',x2,'i')
  

a =3
b =2
c =10
delta = -116
x1 -  (-3-16.15549442140351j) i et x2 =  (-3+16.15549442140351j) i


n! = 1 x 2 x 3 x … x n

In [ ]:
# 3.5 Factorielle
# Ecrire un algorithme qui demande un nombre de d́epart, et qui calcule sa factorielle. On rappel qu’on calcul factorielle n tel que : n! = 􏰁1in i = 1×2×3×...×(n−1)×n.

a = int(input('saisir une valeur :'))
factorielle = 1

for eachInteger in range(1,a):
  factorielle = factorielle * eachInteger

print(factorielle)

saisir une valeur :5
24


In [ ]:
#def factoriel(val):
#  result=1


def fact(n):
  """fact(n): calcule la factiorielle de n (entier >= 0)"""
  if n<2:
    return 1
  else:
    return n*fact(n-1)

fact(-5)

1

In [ ]:
# Coefficients binomiaux

n = int(input('valeur n: '))
k = int(input('valeur k: '))

def fact(n):
  """fact(n): calcule la factiorielle de n (entier >= 0)"""
  if n<2:
    return 1
  else:
    return n*fact(n-1)

coeff = (fact(n) / (fact(k)*((fact(n-k)))))

print(coeff)

valeur n: 10
valeur k: 5
252.0


In [ ]:
from math import factorial
import scipy.special

print(scipy.special.binom(10,5))

n = int(input())
k = int(input())

A = factorial(n) / (factorial(k) * factorial(n - k))

print(A)

252.0
10
5
252.0


In [ ]:
i

In [ ]:
# saisie de matrice

import numpy as np

matrixArr = []
matrixCol = int(input('Nombre de colonnes :'))
matrixLines = int(input('Nombre de lignes :'))
values = 0

# entries possibles
values = matrixCol * matrixLines

# for value in values
for v in range(1, values + 1):
  # get the user value defined
  getVal = int(input('Saisissez la valeur : {}'.format(v)))
  # append the value to the matrixArr
  matrixArr = np.append(matrixArr, getVal)
  

# create the matrix
B = matrixArr.reshape(matrixCol, matrixLines)

print(B)

Nombre de colonnes :2
Nombre de lignes :3
Saisissez la valeur 11
Saisissez la valeur 223
Saisissez la valeur 323232
Saisissez la valeur 49
Saisissez la valeur 5121
Saisissez la valeur 6998
[[1.0000e+00 2.3000e+01 2.3232e+04]
 [9.0000e+00 1.2100e+02 9.9800e+02]]


In [ ]:
# correction
import numpy as np

n = int(input('n ='))
p = int(input('p ='))

taille = int(input('Entrer la taille de la liste'))
tableau = [0]*taille

for i in range(taille):
  tableau[i] = int(input('Entrer une valeur'))

print(tableau)
m = np.array(tableau)
m = m.reshape(n,p)
print(m)

In [ ]:
m=int(input("col")) # nombre de colonnes
p=int(input("lignes")) # nombre de lignes

for i in range(m):
    # parcourir les colonnes de B
    for j in range(p):
        # parcourir les lignes de B
        C[i][j] = input("valeur:")

print (C)

col2
lignes3
valeur:12


IndexError: ignored

In [ ]:
# multiplication matricielle

import numpy as np

cols = int(input('Nombre des colonnes :'))
lines = int(input('Nombre des lignes :'))

values = cols * lines
valuesA = []
valuesB = []

for i in range(1,values + 1):
  #valuesArray.append(int(input('Entrer une valeur {}:'.format(i))))
  valuesA.append(i)

for j in range(1, values + 1):
  #valuesArray.append(int(input('Entrer une valeur {}:'.format(i))))
  valuesB.append(j*2)


def createMatrix(array, cols, lines):  
  a = np.array(array)
  return np.reshape(a,(lines,cols))

matrixA = createMatrix(valuesA, cols, lines)
matrixB = createMatrix(valuesB, cols, lines)

print(matrixA)
print(matrixB)


Nombre des colonnes :3
Nombre des lignes :4
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]
 [20 22 24]]


In [ ]:
# correction multiplication matricielle 
def produitMatriciel(A, B):
    n = len(A)
    p = len(A[0])
    q = len(B[0])
    return list([sum([A[i][k]*B[k][j] for k in range(p)]) for j in range(q)] for i in range(n))


A = [[1,2], [3,4]]
B = [[1,2], [3,4]]
print (produitMatriciel(A,B))

#avec numpy
import numpy as np 

np.dot(A,B)