<a href="https://colab.research.google.com/github/tekebim/exo-algo/blob/master/NumpyExo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy exercices pratiques
Ce notebook à pour objectif de vous faire pratiquer numpy dans toute sa généralité. 
Vous avez donc une liste de questions à faire ! Il ne faut pas hésiter à faire des recherches sur google ainsi que voir la [documentation officielle](https://docs.scipy.org/doc/numpy-1.13.0/reference/). 

#### Q1 : Importer le package numpy 

In [3]:
import numpy as np

#### Q2 : Afficher la version de numpy et la configuration 

In [5]:
np.version.version

'1.18.5'

#### Q3 : Créer un vecteur nul de taille 10

In [14]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### Q4 : Créer un vecteur null de taille 10 et affecter la valeur 1 à la 4ème place (index 4) du vecteur

In [15]:
x = np.zeros(10)
x[4] = 1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### Q5 : Créer un vecteur Z de 40 valeurs allant de 10 à 50 

In [20]:
z = np.random.randint(low = 10, high = 50, size = 40)
print(z)

[47 12 22 42 31 35 42 20 32 20 15 37 17 23 42 30 33 43 33 31 19 31 40 45
 31 31 42 47 14 40 21 29 11 29 41 49 27 36 41 31]


#### Q6 : Inverser Z (le premier élément devient donc le dernier)

In [21]:
z = z[::-1]
print(z)

[31 41 36 27 49 41 29 11 29 21 40 14 47 42 31 31 45 40 31 19 31 33 43 33
 30 42 23 17 37 15 20 32 20 42 35 31 42 22 12 47]


#### Q7 : Créer une matrice 3x3 avec des valeurs comprise entre 0 et 8 

In [28]:
m3x3 = np.random.randint(low = 0, high = 8, size = 9).reshape(3,3)
print(m3x3)

[[5 5 3]
 [7 5 7]
 [4 6 1]]


#### Q8 : Créer une matrice identié 3x3 

In [40]:
mdiag = np.zeros((3, 3), int)
np.fill_diagonal(mdiag, 1)
print(mdiag)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


#### Q9 : Créer une matrice 3x3x3 avec des valeurs random 

In [30]:
m3x3x3rand = np.random.rand(3,3,3)
print(m3x3x3rand)

[[[0.06458809 0.23732379 0.72007607]
  [0.46740692 0.9635118  0.16015938]
  [0.41355432 0.31835559 0.76899839]]

 [[0.86188193 0.1722254  0.90699368]
  [0.87689307 0.52630585 0.50679221]
  [0.94187749 0.39324641 0.8994743 ]]

 [[0.90566373 0.81181833 0.32834296]
  [0.75160963 0.07276028 0.17813806]
  [0.41082265 0.06736026 0.23736296]]]


#### Q10 : Créer une matrice 10x10 avec des valeurs random et afficher le minimum et maximum de cette matrice

In [31]:
m10x10rand = np.random.rand(10,10)
m10x10min = np.min(m1010rand)
m10x10max = np.max(m1010rand)

print('minimum:',m10x10min)
print('maximum',m10x10max)
print(m10x10rand)

minimum: 0.006089822280276991
maximum 0.9937491978944998
[[0.36181927 0.78667539 0.08859476 0.17548342 0.77050052 0.6368447
  0.19204925 0.63918341 0.92347303 0.3676513 ]
 [0.63827294 0.5746923  0.80912626 0.31403796 0.73310049 0.37497725
  0.56126191 0.28185642 0.30129956 0.22854622]
 [0.63999638 0.73151322 0.43700071 0.72346177 0.44332386 0.73515665
  0.17301864 0.70373959 0.09047979 0.88116557]
 [0.74659369 0.39065173 0.73009132 0.05610268 0.55254649 0.73142889
  0.88328778 0.99348401 0.82667046 0.30797294]
 [0.59752168 0.8118939  0.34466921 0.73498144 0.91896958 0.78656492
  0.67200914 0.82069557 0.33480318 0.45921382]
 [0.39096057 0.18576682 0.45490411 0.28296036 0.57517071 0.94002216
  0.60641306 0.15487669 0.29099413 0.31975837]
 [0.79125281 0.59601533 0.7384016  0.81621998 0.88402527 0.82088983
  0.5957766  0.73319004 0.04759002 0.05949939]
 [0.24303388 0.50772455 0.06242068 0.8392686  0.15849325 0.33563317
  0.72152489 0.61753158 0.3769316  0.65821469]
 [0.29967148 0.51841143 

#### Q11 : Créer une matrice 5x5 avec les valeurs 1,2,3,4 en dessous de la diagonale 

In [39]:
#m5x5 = np.random.rand(5,5)
m5x5 = np.random.uniform(low = 1, high = 4, size = (5,5))
print(m5x5)

[[2.17097949 2.79419392 1.41788446 2.36674229 3.95057796]
 [2.15212671 3.25830022 2.01980207 1.8628044  3.11279772]
 [1.97122269 1.9236785  3.51578785 3.72401185 3.48893236]
 [3.82675652 1.11812162 3.47981168 2.23519015 1.60803156]
 [1.15846888 1.94692575 1.23404009 1.41594085 2.22511386]]


#### Q12 : Créer une liste random de taille 5 et donner la somme de ses éléments  

#### Q13 : Créer une liste random de taille 5 et donner la moyenne de ses éléments

#### Q14 : En utilisant une fonction, donner la taille de la liste suivante :
```python 
l = [x for x in range(11)]
```

#### Q15 : Créer un tableau de taille 10 avec des valeurs comprises entre 0 et 1 EXCLUS 

#### Q16 : Soit deux tableau A et B de dimension 1 et de taille 5, créer A et B et afficher True si A et B sont égaux False sinon

#### Q17 : Convertir un tableau de float32 de dimension 1 et de taille 10 en un tableau de meme taille et dimension mais de type int32

#### Q18 : Normaliser une matrice random 5x5 
La normalisation d'un nombre X consiste à lui retirer sa moyenne et a diviser le tout par son écart type 

#### Q19 : Créer une matrice random `M` 2x2 et donner sa transposer 
L'opération de transposition dans une matrice consiste à échanger les lignes et le colonnes. 

#### Q20 : Écrire un petit script qui remplace un élément au hasard dans une matrice de dimension NxN

#### Q21 : Considérons une matrice de dimension (5,5,3), écrire un script qui multiplie cette matrice par une matrice de dimension (5,5)